---
title: R in Trust - A Case study of SARS-CoV2 Open Data Repositories 
authors:
  - name: Nathanael Sheehan
    department:  College of Engineering, Mathematics and Physical Sciences 
    affiliation: Exeter University
    location: University of Exeter, St Germans Road, EX4 7HD Exeter, UK
    email: ns651@exeter.ac.uk
  - name: Sabina Leonelli
    department: EGENIS, Centre For The Study Of Life Sciences
    affiliation: Exeter University
    location: University of Exeter, St Germans Road, EX4 7HD Exeter, UK
    email: s.leonelli@exeter.ac.uk
abstract: |
  In this paper I aruge on the importance of TRUST 
keywords:
  - SARS-CoV2
  - Open Science
  - Data Governance
bibliography: references.bib
biblio-style: unsrt
output: rticles::arxiv_article
---

# Introduction


The pandemic highlighted the necessity for rapid, scalable and open access to the latest research findings, treatments and protocols on the cornavirus. This shift in research practice - in conjunction with decreasing costs in data storage - has led to an exponential increase of data respotitores publically avalaalible on the internet. The biological entity scietifically known 
Among the vast digital sea of data reposotories the usual authorities who steer the direction of power and resources are present, Governments and Universities were among the first to adopt OS principles in practice, daily updates of cases testing, vaccine progress, epistomeoglocial roots interali   

it takes a great deal of work to sucessfully collect, store and manage data 
and among the hundreds of thousands of reposotoires which have come online since the pandemic

in cyberspace and are owned and mangaged by an array of Governments, Universities, Businesses and publics. 


Data repostiores have been buuilt by Governments, univieristies, busisinerses and publics
The greatest example of this has been the sharing of SARS genomic data, where millions of genomes have been shared across the world 
During the Pandemic an open letter was written by the EBI in support in complete openness in genome sharing and asked for people to donate all data to a traid of databases
Many public figures and institutions supported the letter saying that coivd was bigger than all of us, and we must come together
Others critiseied the letter and argued that there database was a wolf in open source clothing and missed the point in resonsibility for data sharing

 in "big" data and public repositories that stores such data. This new found importance for data repostiores mea 


TRUSt is a set of principles for data repositiores owners to adhere to so the community is served and they demonstate the ability to mananage the data they hold
T = transparancey U = User focus, S = Sustainablity, T = Trust
R = Adhering to the designated community’s metadata and curation standards, along with providing stewardship of the data holdings e.g. technical validation, documentation, quality control, authenticity protection, and long-term persistence.

Providing data services e.g. portal and machine interfaces, data download or server-side processing.

Managing the intellectual property rights of data producers, the protection of sensitive information resources, and the security of the system and its content.

The FAIR Data Principles3 highlight the need to embrace good practice by defining essential characteristics of data objects to ensure that data are reusable by humans and machines 
The Open Archival Information System (OAIS) reference model4 provides recommendations on setting up archives delivering long-term preservation of and access to information (in particular, digital information) and creating preservation packages.
None of these encapsulate trust and tremporal demand that trust takes to build and serve a community
[trust table ]

To start I document my expereince joining each community and qualiotaitely narrate me expereince conceptaulising the R principles in each repo
I then systhensis the datasets into aggreated months and explore statistical trends in each dataset
I conclusde by a final discourse on how 

# Methods

```{r fig2, fig.cap = "Monthly totals of global SARS-CoV-2 cases sequenced and shared\n on the GISAID and Covid-19 Data Platform database until Febuary 22 2022", echo=FALSE, message=FALSE, warning=FALSE}
source("../code/set-up.r")
main_df = readRDS("../data/main_df.rds")
temporal_sub_all = readRDS("../data/temporal_sub_all.rds")
ggplot(data=temporal_sub_all) +
  geom_line(aes(x=Date,y=sum_gisaid, group=1, color='GISAID Monthly Total')) +
  geom_line(aes(x=Date,y=sum_cd19dp, group=1, color ='CD19DP Monthly Total')) +
  scale_colour_manual("",
                      breaks = c("GISAID Monthly Total", "CD19DP Monthly Total"),
                      values = c("green", "blue")) +
  labs(x = "Date",
       y = "Sequence Submissions",
       title = "Monthly Total SARS-CoV-2 Sequence Submissions",
       caption = "GISAID Metadata: https://www.epicov.org/\nCovid-19 Data Platform Metadata: https://www.ebi.ac.uk/ena/portal/api/ ") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5),   legend.position = "bottom")


```




## GISIAD

In May of 2008 the Global Initiative on Sharing All Influenza Data (GISAID) was launched in tandem with the Sixty-first World Health Assembly. GISAID 
From its inceptions GISAID was built to be an alternative to the classical public domain sharing model as it took into account the beliefs of Member states by providing an accessible database designed by scientists for scientists. 


## COVID-19 Data Platform

# Discussion

# Conclusion


